fixed redirection of reset Password
atlp-rwanda/e-comm-team-brogrammers-bn pull request #106
Opened 2023-05-31 19:06 UTC by bencyubahiro77

#### What does this PR do?
this pr is a fix of redirection to the frontend URL after resetting Password

#### Description of Task to be completed?
this task is a fix of redirection to the frontend URL after resetting Password when a user successfull reset the password

#### How should this be manually tested?

- try to reset the password then check your email to verify the reset Password token
- after click the button you get the you will be redirected to the success page

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2023-05-31 23:07 UTC, UmuhireJessie requested changes
Provide screenshots!

2023-06-01 08:50 UTC, UmuhireJessie approved these changes

2023-06-01 09:18 UTC, edwinnambaje approved these changes

2023-06-01 09:57 UTC, blackd44 approved these changes

2023-06-01 12:12 UTC, Martha-Iradukunda approved these changes

2023-06-01 14:37 UTC, UmuhireJessie approved these changes

2023-06-01 14:38 UTC, merged