(fix-but)redirection after  email verification
atlp-rwanda/e-comm-team-brogrammers-bn pull request #109
Opened 2023-06-01 12:21 UTC by Patienceineza

#### What does this PR do?

fix-bug in redirection after successfull email verification

#### Description of Task to be completed?

-remove json and add frontend page for verification

#### How should this be manually tested?

-check email  after signup

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)
<img width="1424" alt="Screenshot 2023-06-01 at 14 08 21" src="https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn/assets/99663528/7080e9ae-3f35-43e9-babb-6257e850860b">

#### Questions:

2023-06-01 13:44 UTC, Zeden12 approved these changes

2023-06-01 13:48 UTC, bencyubahiro77 requested changes
you can put that url in the env

2023-06-01 16:03 UTC, bencyubahiro77 approved these changes

2023-06-02 09:56 UTC, UmuhireJessie approved these changes

2023-06-02 09:56 UTC, merged