Ft config 184581317
atlp-rwanda/e-comm-team-brogrammers-bn pull request #11
Opened 2023-03-02 14:00 UTC by Patienceineza

This pull request is for the activity of connecting postgres database and it is now working perfectly . to be able to to run  this you will have to configure the following in your .env file

your DATABASE_URL : in this format postgres://<db_user>:<db_password>@127.0.0.1:5432/dev_db
db_user: as your username
db_password:password to your database
dev_db: as your database name

2023-03-03 14:06 UTC, bencyubahiro77 approved these changes
use PR template

2023-03-03 16:41 UTC, INValentin approved these changes
Checked it and it worked!

2023-03-06 13:33 UTC, blackd44 approved these changes
I see hound is bringing error `process not defined` but from me there is no problem,
it LGTM

2023-03-06 13:38 UTC, blackd44 commented on src/database/config/config.js
> +    url: process.env.DEV_DATABASE_URL,
i see no problem with this

2023-03-06 17:41 UTC, nshutijonathan requested changes
Please solve conflicts

2023-03-06 21:04 UTC, Patienceineza commented
just resolved the conflicts please review

2023-03-06 21:22 UTC, edwinnambaje approved these changes
LGTM

2023-03-07 17:04 UTC, closed without merging