Using docker-compose to run the app and connect successfully to a pos…
atlp-rwanda/e-comm-team-brogrammers-bn pull request #12
Opened 2023-03-02 19:03 UTC by INValentin

### What does this PR do?
Setup docker-compose to run backend and database applications

### Description of Task to be completed

- Installing docker/docker-compose
- Creating docker images for node backend & postgres database applications
- Making sure the node backend can connect to postgres database

### installed packages
- sequelize (for testing db connection)

### How should this be manually tested
- Install [docker](https://www.docker.com/products/docker-desktop/) & docker compose
- `cd to/project/directory` (after cloning)
- `npm install` 

### Any background context you want to
n/a

2023-03-03 09:07 UTC, Patienceineza commented
LGTM

2023-03-03 14:08 UTC, bencyubahiro77 approved these changes
everything is fine

2023-03-03 14:18 UTC, edwinnambaje requested changes
I think the title of your PR is lacking the pivot tracker id

2023-03-03 15:19 UTC, blackd44 approved these changes
Better to me

2023-03-05 09:04 UTC, bencyubahiro77 approved these changes

2023-03-05 19:55 UTC, nshutijonathan commented
> I think the title of your PR is lacking the pivot tracker id

He should rename his PR the way it is supposed to be.

2023-03-05 20:24 UTC, Zeden12 approved these changes
LGTM

2023-03-05 22:01 UTC, INValentin commented
> > I think the title of your PR is lacking the pivot tracker id
> 
> He should rename his PR the way it is supposed to be.

My bad title fixed!

2023-03-06 06:56 UTC, edwinnambaje approved these changes
LGTM

2023-03-07 17:02 UTC, nshutijonathan requested changes
Hey @INValentin 
Squash your commits into one and resolve conflicts

2023-03-07 17:39 UTC, nshutijonathan requested changes

2023-03-07 17:39 UTC, nshutijonathan commented on .env.example
> +<<<<<<< HEAD
Hey 

These are conflicts pushed ,fix them

2023-03-07 18:52 UTC, nshutijonathan approved these changes
LGTM

2023-03-07 18:53 UTC, merged