Feature(login) Added user login #184581331
atlp-rwanda/e-comm-team-brogrammers-bn pull request #23
Opened 2023-03-10 07:25 UTC by INValentin

#### What does this PR do?
This PR is to add user login to the backend application
#### Description of Task to be completed?

- Add user login routes, controller, middleware for validation
- Authenticate users with correct **verified** email and password
- Deny Authentication for incorrect or **unverified** credentials

#### How should this be manually tested?
- First make sure you run **migrations** `npm run migrate:all`
- Try logging in with **email** and **password** but make sure email is **verified** by providing 
 a **POST** request at `/users/login/` 
- You should get a response corresponding to your credentials, and if you're good you get a **JWT token**, other wise
you should get a **message** explaining the issue.
#### Any background context you want to provide?
- Running migrations is important
#### What are the relevant pivotal tracker/Trello stories?
- `https://www.pivotaltracker.com/n/projects/2632830/stories/184581331` 
#### Screenshots (if appropriate)

#### Questions:

2023-03-10 08:28 UTC, nshutijonathan requested changes
- This PR title is wrong`Feature(login) Added user login #184581331 ` ,please correct it 

- Add two screenshots in your PR, the one showing passing tests of yours and the swagger  showing how user login works 

- Update your Readme to show how login JSON values are passed, please refer to sign-up.

2023-03-10 08:32 UTC, nshutijonathan requested changes

2023-03-10 08:32 UTC, nshutijonathan commented on src/db.js
> +// const dbUser = process.env.POSTGRES_USER
Don't push commented-out codes , always remember to get rid of them before shipping your codes

2023-03-10 08:32 UTC, nshutijonathan commented on src/db.js
> +// const sequelize = new Sequelize(`postgres://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}`)
Commented out codes should not be pushed

2023-03-10 08:32 UTC, nshutijonathan commented on src/routes/auth.routes.js
> +  'goK!pusp6ThEdURUtRenOwUhAsWUCLheBazl!uJLPlS8EbreWLdrupIwabRAsiBu';
This sensitive info should be loaded from the `env` file

2023-03-10 10:41 UTC, blackd44 approved these changes

2023-03-10 10:41 UTC, blackd44 commented on src/controllers/users.controllers.js
> +  static async login(req, res) {
you need to add try and catch in controllers in other to avoid crashing in server.

2023-03-10 10:49 UTC, blackd44 reviewed
<img width="1014" alt="Screen Shot 2023-03-10 at 12 47 46" src="https://user-images.githubusercontent.com/112763782/224296905-aaae887f-4e97-4d29-ab86-e75d70cca668.png">
you need to add those users in seeder verified

2023-03-10 11:27 UTC, Zeden12 approved these changes
LGTM

2023-03-10 14:52 UTC, edwinnambaje approved these changes
LGTM

2023-03-13 07:29 UTC, nshutijonathan requested changes

2023-03-13 07:29 UTC, nshutijonathan commented on src/routes/auth.routes.js
> +  'goK!pusp6ThEdURUtRenOwUhAsWUCLheBazl!uJLPlS8EbreWLdrupIwabRAsiBu';
Please get the token from `.env` you should not push sensitive information like that

2023-03-13 09:32 UTC, blackd44 requested changes

2023-03-13 09:32 UTC, blackd44 commented on src/controllers/users.controllers.js
> +      const token = jwt.sign({ ...user }, JWT_SECRET);
I think we don't need to add whole user in jwt for security reason
better can be like `email` or `id` because are unique.
try to mimic for that on on signup

2023-03-13 10:46 UTC, blackd44 commented on tests/login.test.js
> +    });
we don't need to delete `admin` and `sellers`
yo can try this to delete others
```
import { Op } from 'sequelize';
.
.
.
where: { 
    role: { 
        [Op.not]: ['admin', 'seller'] 
    } 
}
```

2023-03-13 13:13 UTC, blackd44 approved these changes
LGTM

2023-03-13 15:59 UTC, nshutijonathan approved these changes
LGTM

2023-03-13 15:59 UTC, merged