Feature(Authorization):Protecting routes #184581333
atlp-rwanda/e-comm-team-brogrammers-bn pull request #24
Opened 2023-03-10 08:13 UTC by Patienceineza

#### What does this PR do?
this  PR is for authentication or protection of routes 
#### Description of Task to be completed?

this task is associated with creating a middleware that will check if there is token in bearer auth and return an error otherwise it will verify that token and  either give access to user or deny access

#### How should this be manually tested?

-  after cloning the repo `write npm run drop` to drop previous tables and database

-  run `npm run migrate:all ` to run seeds and migrations
- and finally  run` npm install ` to install all necessary packages
- then go to where you test your api and use the correct End point to make sure it orks

#### Any background context you want to provide?

N/a

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184581333

#### Screenshots (if appropriate)

#### Questions:

2023-03-10 08:36 UTC, nshutijonathan requested changes
- Rename the title of your PR, It should not be like that 
- Rename your commit message from `Feature(Authorization):Protecting routes #184581333` to `feat(authorization):protecting routes` .

2023-03-13 11:42 UTC, edwinnambaje approved these changes
LGTM

2023-03-13 11:50 UTC, Zeden12 approved these changes
LGTM

2023-03-13 12:07 UTC, blackd44 approved these changes

2023-03-13 14:18 UTC, nshutijonathan requested changes

2023-03-13 14:18 UTC, nshutijonathan commented on src/controllers/users.controllers.js
> +    console.log('User Verified Successfully');
remove `console.log`

2023-03-13 14:18 UTC, nshutijonathan commented on src/routes/auth.routes.js
> +  'goK!pusp6ThEdURUtRenOwUhAsWUCLheBazl!uJLPlS8EbreWLdrupIwabRAsiBu';
Hide the token, don't pass it here, It should be loaded from the `.env` file

2023-03-13 14:49 UTC, nshutijonathan approved these changes
LGTM

2023-03-13 14:49 UTC, merged