Feature( login with google):signin with google account #184581332
atlp-rwanda/e-comm-team-brogrammers-bn pull request #32
Opened 2023-03-14 12:34 UTC by Habihirwe

**What does this PR do?**

allows user to login with google account

**Description of Task to be completed?**

first we check wether the email of the user is in data base 
if yes  it displays the success message, the token , and the role of user.

**endpoints:**

/auth/auth/google/callback

**How should this be manually tested?**

after cloning the repo,
you have to create the client credentials
so that you can get 
-clientID
-clientSecret
-callbackURL
in terminal add npm install

- add .env in your repo and assign the variables as there are in .env.example file
- run in termainal npm run migrate:all to setup the database
- run in termainal npm start to start the project
- in your browser add http://localhost:<your port>/auth/auth/google/callback

**Any background context you want to provide?**
n/a

**What are the relevant pivotal tracker/Trello stories?**

https://www.pivotaltracker.com/story/show/184581332

**Screenshots (if appropriate)**

**Questions:**
n/a

2023-03-14 12:57 UTC, blackd44 requested changes
Others Looks Good

2023-03-14 12:57 UTC, blackd44 commented on src/routes/auth.js
> +      if (userObj.email_verified != true) return res.status(401).json({ message: "Email not verified", error: true });
can you change `userObj.email_verified` to `userObj.verified` in order to much with others tasks as:
<img width="841" alt="Screen Shot 2023-03-14 at 14 53 59" src="https://user-images.githubusercontent.com/112763782/225006939-2a0a9c7e-efac-4671-9de7-c83ce8dc1be2.png">

2023-03-14 12:57 UTC, blackd44 commented on src/routes/auth.js
> +      console.error(err);
remove `console`

2023-03-14 13:20 UTC, nshutijonathan requested changes
The title of your PR is not the right one ,please correct is

2023-03-14 13:20 UTC, nshutijonathan commented on src/routes/auth.js
> +            clientID: "1072588531381-nmcmlfa0m0a2tmu5lqh18bc1lrec23t9.apps.googleusercontent.com",
this is sensitive information and should be loaded from the `env` file

2023-03-14 13:20 UTC, nshutijonathan commented on src/routes/auth.js
> +            clientSecret:"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" ,
clientSecret should not be exposed to the public

2023-03-14 13:31 UTC, Patienceineza approved these changes
LGTM

2023-03-14 14:27 UTC, edwinnambaje approved these changes
Fix changes you had been requested to do otherwise LGTM

2023-03-14 14:29 UTC, edwinnambaje requested changes
fix changes you had been requested to do and also conflicts with the tests

2023-03-15 21:41 UTC, nshutijonathan approved these changes
LGTM

2023-03-17 10:25 UTC, Zeden12 approved these changes
LGTM

2023-03-17 10:27 UTC, Zeden12 commented
fix the conflicts with the tests and you're ready to move

2023-03-17 11:54 UTC, Martha-Iradukunda reviewed
LGTM

2023-03-17 11:56 UTC, Martha-Iradukunda approved these changes

2023-03-17 13:04 UTC, edwinnambaje approved these changes
LGTM

2023-03-17 15:15 UTC, blackd44 approved these changes

2023-03-17 15:16 UTC, blackd44 commented
solve those conflicts

2023-03-17 19:28 UTC, INValentin approved these changes
LGTM

2023-03-17 22:27 UTC, UmuhireJessie approved these changes

2023-03-17 22:27 UTC, merged