#184581335 Add Multi-Factor Authentication(MFA)
atlp-rwanda/e-comm-team-brogrammers-bn pull request #34
Opened 2023-03-14 15:31 UTC by INValentin

#### What does this PR do?
This is to add multi-factor authentication to increase security the login process, for users that turn on MFA.
#### Description of Task to be completed?
GIVEN there is a request to login a user to the website
WHEN 2FA is enabled on the particular user
THEN Further request for a 2FA code is requested and once the code is received and validated, the user is allowed to login(via a jwt token).
#### How should this be manually tested?

- run `npm install`
- run `npm run migrate:all`
- run `npm run start`
- Login a new user
- Enable MFA with `POST` request at `/users/enable-mfa` providing a valid token for auth
- Try logging in again, now you shouldn't get a token instead message to check your inbox
- Copy the the code and sent it with `POST` to `/users/verify-mfa` you should get a jwt token

#### Any background context you want to provide?
- To disable MFA a `POST` request can be sent to `/users/disable-mfa` with valid jwt token
#### What are the relevant pivotal tracker/Trello stories?
[https://www.pivotaltracker.com/n/projects/2632830/stories/184581335](url)
#### Screenshots (if appropriate)
<img width="1012" alt="Screenshot 2023-03-14 at 16 53 45" src="https://user-images.githubusercontent.com/57767759/225052641-86b0e678-8f8f-4f7f-b6bb-a999a8e826c1.png">
<img width="1256" alt="Screenshot 2023-03-14 at 17 22 08" src="https://user-images.githubusercontent.com/57767759/225052686-faaf1a65-1c21-4e30-8a49-70c8f68bf6c6.png">

#### Questions:

2023-03-14 15:46 UTC, Patienceineza approved these changes
LGTM

2023-03-14 15:59 UTC, edwinnambaje approved these changes
LGTM

2023-03-14 23:41 UTC, UmuhireJessie requested changes
Good work Valentin! Please note:
1. Rebase to the develop
2. Tests are failing
![Screenshot from 2023-03-15 01-37-41](https://user-images.githubusercontent.com/86103578/225165938-b9e5ec46-bc09-4f30-adeb-95741007f9af.png)

2023-03-15 06:10 UTC, INValentin commented
> Good work Valentin! Please note:
> 
> 1. Rebase to the develop
> 2. Tests are failing
>    ![Screenshot from 2023-03-15 01-37-41](https://user-images.githubusercontent.com/86103578/225165938-b9e5ec46-bc09-4f30-adeb-95741007f9af.png)

2023-03-15 11:59 UTC, nshutijonathan approved these changes
LGTM

2023-03-15 13:12 UTC, blackd44 approved these changes
other looks good

2023-03-15 13:12 UTC, blackd44 commented on src/database/migrations/20230314092003-add_mfa_code_to_users_table.js
> +        queryInterface.addColumn(
can you add those columns in `20230308210129-create-users.js` migration file instead of adding other migration file

2023-03-15 13:39 UTC, UmuhireJessie approved these changes
Good!

2023-03-15 16:23 UTC, bencyubahiro77 approved these changes

2023-03-16 09:24 UTC, nshutijonathan approved these changes
LGTM

2023-03-16 09:59 UTC, merged