#184581334 feature (reset-password)
atlp-rwanda/e-comm-team-brogrammers-bn pull request #41
Opened 2023-03-19 10:16 UTC by INValentin

#### What does this PR do?
This PR is to add the ability for users to reset their passwords via email whenever they forget them. 

#### Description of Task to be completed?
GIVEN I forget my password
WHEN I request for a reset
THEN I should receive an email with a reset link to the application.
#### How should this be manually tested?
To test this manually follow the following guide:

- clone the repo (or branch)
- Please add environment variables mentioned below (in background context)
- run `npm install && npm run migrate && npm start`
- After the server is running create a user through `/api-docs` or using some API client
- After creating a user ask for reset password link by providing `{email: "mail", newPassword: "@!#"}` 
- The link for reset should be sent to your email, click the link and your password **should get reset**
- Use the new password for usual logins to verify

#### Any background context you want to provide?
####You must have the following environment variables (**contact valentin** to get _secrets_)
- `EMAIL=email@used.tosendmails` (contact me)
- `EMAIL_PASSWORD=password!fortheemail` (contact me)
- `PASSWORD_RESET_URL=http://localhost:5000/users/verify-reset-password` (just this one - dont contact me)
- SALTROUND=10

**THIS PR ALSO INCLUDES FIXES TO MULTI-FACTOR AUTHENTICATION AND _EMAILS_**

#### What are the relevant pivotal tracker/Trello stories?
[https://www.pivotaltracker.com/n/projects/2632830/stories/184581334](url)
#### Screenshots (if appropriate)
<img width="1112" alt="Screenshot 2023-03-19 at 11 49 50" src="https://user-images.githubusercontent.com/57767759/226168742-dbaa5b7e-4e16-4c43-b254-0ae7e53c3178.png">
<img width="1262" alt="Screenshot 2023-03-19 at 11 51 51" src="https://user-images.githubusercontent.com/57767759/226168751-4983a2fd-ea90-41f5-ae6b-17b045ff0a90.png">

#### Questions:

2023-03-19 11:38 UTC, edwinnambaje approved these changes
LGTM

2023-03-19 11:50 UTC, blackd44 requested changes
remove `console` in the codes

2023-03-19 12:12 UTC, Martha-Iradukunda approved these changes
LGTM

2023-03-19 15:11 UTC, Zeden12 approved these changes
LGTM

2023-03-19 23:22 UTC, blackd44 approved these changes

2023-03-20 08:51 UTC, UmuhireJessie commented on .env.example
> +EMAIL=<contact valentin for email>
Can you give descriptive names to your variables? According to what they do maybe
Instead of saying "contact someone for this variable"

2023-03-20 08:57 UTC, UmuhireJessie requested changes
Consider giving descriptive names to your environment variables.

You weren't more specific , I noticed email environments needed a change.

2023-03-20 13:19 UTC, UmuhireJessie approved these changes

2023-03-20 13:21 UTC, merged