[184581344] getting product by id
atlp-rwanda/e-comm-team-brogrammers-bn pull request #44
Opened 2023-03-20 15:53 UTC by bencyubahiro77

#### What does this PR do?
To get product by id 

#### Description of Task to be completed?
The buyer will be able to get the product by id from any seller and the seller will only be able to get product by id from his collection only.

#### How should this be manually tested?
after cloning the repo,

- in terminal add ``npm install``

- add ``.env`` in your repo and assign the variables as there are in .env.example file

- run in terminal ``npm run migrate:all`` to setup the database

- run in terminal ``npm start`` to start the project

- in your browser add ``http://localhost:<your port>/api-docs`` for documentantion
- then after succesfully login :

- [ ] if you are a buyer run ``GET`` ``http://localhost:<your port>/products/buyer/productId``
- [ ] if you are a seller run ``GET`` ``http://localhost:<your port>/products/seller/productId``

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581344

#### Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2023-03-20 at 17 49 28" src="https://user-images.githubusercontent.com/118971204/226394272-d7488fba-5f92-46eb-a903-1108e5e8705a.png">

#### Questions:

2023-03-21 13:46 UTC, nshutijonathan commented on src/controllers/products.controllers.js
> +    const validUUID = /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/;
Make this `validUUID` a global variable to avoid creating it multiple times

2023-03-21 13:46 UTC, nshutijonathan commented on src/controllers/products.controllers.js
> +    const validUUID = /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/;
Make this `validUUID` a global variable to avoid creating it multiple times

2023-03-21 13:48 UTC, nshutijonathan requested changes
Check my comments on `validUUID`

2023-03-21 19:28 UTC, Martha-Iradukunda approved these changes
LGTM

2023-03-22 07:46 UTC, nshutijonathan approved these changes
LGTM

2023-03-22 08:09 UTC, edwinnambaje approved these changes
LGTM

2023-03-22 13:53 UTC, merged