Ft product review 184581348
atlp-rwanda/e-comm-team-brogrammers-bn pull request #45
Opened 2023-03-20 18:29 UTC by INValentin

#### What does this PR do?
This PR is to allow buyers to review products by providing a rating and feedback. They also can get, update, or delete their reviews.
#### Description of Task to be completed?
A buyer should be able to provide a review on a product they have bought successfully, rating  and feedback.
#### How should this be manually tested?

- run `npm install && npm run migrate:all && npm run start`
- Then access the API docs on `/api-docs`, from there you can `test the api`.

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581348
#### Screenshots (if appropriate)
<img width="1277" alt="Screenshot 2023-03-20 at 20 25 20" src="https://user-images.githubusercontent.com/57767759/226432804-ee8d8fec-29d9-4608-bb78-319ba2a856c6.png">
<img width="1212" alt="Screenshot 2023-03-20 at 20 27 03" src="https://user-images.githubusercontent.com/57767759/226432898-724bf610-c0b3-49b6-b833-edfabffd94ec.png">

#### Questions:
N/A

2023-03-20 20:34 UTC, edwinnambaje approved these changes
LGTM

2023-03-20 21:23 UTC, Martha-Iradukunda approved these changes
LGTM

2023-03-21 16:24 UTC, nshutijonathan requested changes

2023-03-21 16:24 UTC, nshutijonathan commented on src/services/user.services.js
>        if (err) return console.error('ERROR SENDING MAIL: ', err);
remove `console.log` you can simply `return error.message`

2023-03-21 17:59 UTC, Zeden12 approved these changes
LGTM

2023-03-21 19:21 UTC, bencyubahiro77 approved these changes

2023-03-22 07:48 UTC, nshutijonathan approved these changes
LGTM

2023-03-22 08:39 UTC, UmuhireJessie approved these changes

2023-03-22 08:39 UTC, merged