#184581338 Admin should be able to disable an account for various reasons
atlp-rwanda/e-comm-team-brogrammers-bn pull request #46
Opened 2023-03-20 21:18 UTC by Martha-Iradukunda

#### What does this PR do?
* The PR would likely be adding the feature for an admin to disable a user account and send an email to the user with reasons for the block.
#### Description of Task to be completed?
* The task is to add a feature that allows an admin to disable a user account for various reasons such as fraud, abuse, malicious use or violation of terms of service. The admin should be able to trigger an action to block usage of a particular account and an email should be sent to the user with reasons for the block. Sample violation reasons are provided such as merchants selling illegal items, harassment of other users of the application, and requests from law enforcement.
#### How should this be manually tested?
* Create an admin account and multiple user accounts on the system.
* As the admin, log in to the system and navigate to the user account that needs to be disabled.
* Trigger the action to block usage of the user account.
* Check that the user account has been disabled and the user has received an email with the reasons for the block.
*  Verify that the user is unable to log in to the system.
* PATCH/users/disable/{userId}
#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker/Trello stories?
* [#184581338](https://www.pivotaltracker.com/n/projects/2632830/stories/184581338)

#### Screenshots (if appropriate)
* 
![Screenshot from 2023-03-20 23-12-17](https://user-images.githubusercontent.com/101427855/226466962-9601c2ab-d4d5-435e-97b2-327dc4baed7b.png)
* 
![Screenshot from 2023-03-21 00-17-03](https://user-images.githubusercontent.com/101427855/226468074-963b3664-9c96-4b0f-b289-e0764b48d999.png)

#### Questions:
N/A

2023-03-21 08:27 UTC, edwinnambaje requested changes
You can first solve the tests issues and after you can clearly show us the working in the documentation

2023-03-21 13:41 UTC, nshutijonathan commented on src/controllers/users.controllers.js
> +      console.error(error);
remove `console.log`

2023-03-21 13:42 UTC, nshutijonathan reviewed
remove `console.log`

2023-03-21 19:08 UTC, blackd44 approved these changes
LGTM

2023-03-21 19:08 UTC, edwinnambaje approved these changes
LGTM

2023-03-21 19:20 UTC, bencyubahiro77 approved these changes

2023-03-21 19:26 UTC, Patienceineza approved these changes
LGTM

2023-03-21 21:30 UTC, Zeden12 approved these changes
LGTM

2023-03-22 08:49 UTC, nshutijonathan reviewed
remove console.log

2023-03-22 08:49 UTC, nshutijonathan commented on src/controllers/users.controllers.js
> +      console.error(error);
remove `console.log`

2023-03-22 09:11 UTC, UmuhireJessie requested changes
See my comment

2023-03-22 09:11 UTC, UmuhireJessie commented on src/controllers/users.controllers.js
> +        content: `Dear ${user.username},<br/>
Good job here @Martha-Iradukunda!
For consistency, make sure the email sent to the users looks the same.

2023-03-22 09:16 UTC, Martha-Iradukunda commented
I don't understand?

On Wed, 22 Mar 2023, 12:12 UmuhireJessie ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> See my comment
> ------------------------------
>
> In src/controllers/users.controllers.js
> <https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn/pull/46#discussion_r1144444393>
> :
>
> > +      if (!user) {
> +        return res.status(404).json({ error: 'User not found' });
> +      }
> +      if (user.disabledUser) {
> +        return res.status(400).json({ message: 'user is already disabled' });
> +      }
> +      user.disabledUser = true;
> +      user.disabledReason = req.body.reason;
> +
> +      await user.save();
> +
> +      sendEmail(emailConfig({
> +        email: user.email,
> +        subject: 'Your account has been disabled',
> +        // eslint-disable-next-line no-undef
> +        content: `Dear ${user.username},<br/>
>
> Good job here @Martha-Iradukunda <https://github.com/Martha-Iradukunda>!
> For consistency, make sure the email sent to the users looks the same.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn/pull/46#pullrequestreview-1352031485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYF2VD5QI45IWFXBZ4YIVILW5K66DANCNFSM6AAAAAAWBUBTLM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-03-22 15:13 UTC, UmuhireJessie approved these changes

2023-03-22 15:14 UTC, merged