#184581358 expired product stop listing
atlp-rwanda/e-comm-team-brogrammers-bn pull request #48
Opened 2023-03-21 15:18 UTC by blackd44

#### What does this PR do?
make the expired product not available on the market

#### Description of Task to be completed?
the expired product are removed on the available products
before being removed the seller is given the email in a give amount of time to be warned
and on the exact day of expiration the product is removed and then give the seller the email again

#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
. Crone jobs
. node schedule
.node mailer

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581358

#### Screenshots (if appropriate)
<img width="1024" alt="Screen Shot 2023-03-21 at 17 08 11" src="https://user-images.githubusercontent.com/112763782/226649812-f3813026-2e86-42f7-8e03-9a0850d1fb4a.png">
<img width="1017" alt="Screen Shot 2023-03-21 at 17 12 18" src="https://user-images.githubusercontent.com/112763782/226651125-e51fbf1c-2407-4f46-80c0-ff6971d2088b.png">

#### Questions:
n/a

2023-03-21 15:56 UTC, edwinnambaje approved these changes
LGTM

2023-03-22 13:34 UTC, nshutijonathan requested changes
I left some comments

2023-03-22 13:34 UTC, nshutijonathan commented on src/helpers/expiredProduct.js
> +    // nothing
you can `return error.message` just in case

2023-03-22 13:34 UTC, nshutijonathan commented on src/middlewares/productExpAll.js
> +    console.log(error);
`return error.message` ,remember console is for debugging only

2023-03-22 17:55 UTC, Patienceineza approved these changes
LGTM

2023-03-22 17:55 UTC, INValentin approved these changes
LGTM

2023-03-22 20:42 UTC, Zeden12 approved these changes
LGTM

2023-03-22 20:49 UTC, nshutijonathan approved these changes
LGTM

2023-03-22 21:25 UTC, UmuhireJessie approved these changes
Good job!

2023-03-22 21:25 UTC, merged