Ch database seeder 184797808
atlp-rwanda/e-comm-team-brogrammers-bn pull request #74
Opened 2023-04-01 08:56 UTC by blackd44

#### What does this PR do?
1. Add the seeders to add default records if database is empty
2. add user avatar and cover picture for his account

#### Description of Task to be completed?
1. the seeders must
    - Add dummy users
    - Add dummy orders
    - Add dummy products
    - and other dummy records
    if the database is empty
2. add user avatar and cover picture for his account
    has the following endpoints
    - `PATCH /users/profile/avatar`
        here is to change the profile picture of the user account
    - `PATCH /users/profile/cover-image`
        here is to change the cover picture of the user account
#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentation
#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/story/show/184797808
#### Screenshots (if appropriate)
<img width="1400" alt="Screen Shot 2023-04-01 at 10 54 06" src="https://user-images.githubusercontent.com/112763782/229276274-4cbbec51-90ac-4ae2-9a0b-6d9e6be712f5.png">
<img width="1419" alt="Screen Shot 2023-04-01 at 10 55 40" src="https://user-images.githubusercontent.com/112763782/229276356-38d07f63-87aa-4fc8-889b-0fff6f672cba.png">

#### Questions:
n/a

2023-04-02 16:48 UTC, Martha-Iradukunda approved these changes

2023-04-02 16:59 UTC, INValentin approved these changes
LGTM

2023-04-02 20:07 UTC, edwinnambaje approved these changes
LGTM but change the title of your PR

2023-04-03 11:31 UTC, UmuhireJessie requested changes
Good job, 
resolve the conversation and conflicts and ensure that all tests are passing

2023-04-03 13:16 UTC, UmuhireJessie approved these changes

2023-04-03 13:16 UTC, merged