#184842362  Newsletter Signup
atlp-rwanda/e-comm-team-brogrammers-bn pull request #86
Opened 2023-04-06 16:41 UTC by edwinnambaje

#### What does this PR do?
Implement Newsletter Signup

#### Description of Task to be completed?
Implement Newsletter Signup

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2023-04-08 17:50 UTC, Martha-Iradukunda approved these changes

2023-04-09 06:40 UTC, blackd44 approved these changes
LGTM

2023-04-09 06:42 UTC, blackd44 commented
but try to remove some `console` in the files

2023-04-10 19:00 UTC, bencyubahiro77 approved these changes

2023-04-11 08:53 UTC, Habihirwe approved these changes
LGTM

2023-04-11 14:57 UTC, UmuhireJessie requested changes

2023-04-11 14:57 UTC, UmuhireJessie commented on src/helpers/mailTemplate.js
I only see updates on a product template. Remember that I can also send other updates, such as our app has a new feature, welcome our new members, we have a promotion, please note emails, etc. We need a dynamic template that can be used in these cases. Not just static to product updates

2023-04-11 18:59 UTC, Patienceineza approved these changes

2023-04-11 22:08 UTC, edwinnambaje commented on src/helpers/mailTemplate.js
i may need you help here because i dont understand if i will need to do a separate template for each of those updates you said or if i will make one and how i will make one that will fit all those updates includes those you said in etc

2023-04-11 22:14 UTC, UmuhireJessie commented on src/helpers/mailTemplate.js
You don’t need to create several templates. You can create one where one is able to provide content ( dynamic content) for any information they want to communicate to subscribers.

2023-04-11 23:13 UTC, edwinnambaje commented on src/helpers/mailTemplate.js
I don't understand that either

2023-04-12 19:10 UTC, Zeden12 approved these changes
LGTM

2023-04-13 16:08 UTC, edwinnambaje commented on src/helpers/mailTemplate.js
Check again for requested changes please

2023-04-13 16:36 UTC, UmuhireJessie approved these changes
I understand that we might need to change the implementation if we want to send different Newsletter topics like the newly hired team, feature updates, promotions on the app, etc., but I am accepting this for now.

2023-04-13 16:38 UTC, merged