feat(fix bug):get correct number of items  pagination
atlp-rwanda/e-comm-team-brogrammers-bn pull request #96
Opened 2023-05-11 13:16 UTC by Patienceineza

#### What does this PR do?

this Pr is for fixing bug in pagination

#### Description of Task to be completed?

the bug is that pagination returned incorrect number of items in all pages  

#### How should this be manually tested?

-run any get all endpoint like `/products`

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/185157300
#### Screenshots (if appropriate)

#### Questions:

2023-05-11 14:46 UTC, denislohan requested changes
1. PR named wrong with respect to our conventions

2023-05-11 17:38 UTC, blackd44 approved these changes
LGTM

2023-05-12 09:58 UTC, denislohan approved these changes

2023-05-12 10:07 UTC, INValentin approved these changes

2023-05-12 11:29 UTC, UmuhireJessie approved these changes

2023-05-12 11:30 UTC, merged